platform :ios, "8.0"
use_frameworks!

target “WYLearnSwift” do
pod "SnapKit"
pod "Kingfisher"
pod "SVProgressHUD"
pod "FDFullscreenPopGesture", "~> 1.1"
pod "Alamofire"
pod "SwiftyJSON"
pod "MJRefresh"
pod 'AFNetworking', '~> 3.1.0'

end
